name: Continuous Integration

on:
  push:
    branches: [ surf-webkit2 ]
  pull_request:
    branches: [ surf-webkit2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - image: artixlinux/base
          - image: archlinux
    steps:
      - uses: actions/checkout@v2
      - name: Install Build Dependencies
        run: pacman --noconfirm -Syu && pacman --noconfirm -S make gcc
      - name: Build
        run: make

